@startuml {{NAME}}

title {{TITLE}}

package "{{PACKAGE1}}" {
  [{{COMPONENT1}}]
  [{{COMPONENT2}}]
}

package "{{PACKAGE2}}" {
  [{{COMPONENT3}}]
  [{{COMPONENT4}}]
}

database "{{DATABASE}}" {
  [{{DATA_STORE}}]
}

[{{COMPONENT1}}] --> [{{COMPONENT3}}] : {{RELATION1}}
[{{COMPONENT2}}] --> [{{DATA_STORE}}] : {{RELATION2}}

@enduml
