@startuml {{NAME}}

title {{TITLE}}

actor {{ACTOR1}} as User
participant {{PARTICIPANT1}} as System1
participant {{PARTICIPANT2}} as System2
database {{DATABASE}} as DB

User -> System1: {{REQUEST1}}
activate System1

System1 -> System2: {{REQUEST2}}
activate System2

System2 -> DB: {{QUERY}}
activate DB
DB --> System2: {{RESPONSE}}
deactivate DB

System2 --> System1: {{RESPONSE2}}
deactivate System2

System1 --> User: {{RESPONSE1}}
deactivate System1

@enduml
